import json
from jinja2 import Template

HTML_TEMPLATE = """<!doctype html>
<html><head><meta charset="utf-8"><title>MoneyScan — {{ data.url }}</title>
<style>
body{font-family:system-ui,sans-serif;max-width:900px;margin:2rem auto;padding:0 1rem;color:#111}
h1{margin-bottom:.2rem}
.sev{display:inline-block;padding:2px 8px;border-radius:4px;color:#fff;font-size:.8rem}
.critical{background:#b00020}.high{background:#e65100}.medium{background:#f9a825;color:#000}
.low{background:#2e7d32}.info{background:#555}
.card{border:1px solid #ddd;border-radius:8px;padding:1rem;margin:1rem 0}
.card h3{margin:0 0 .5rem}
.meta{color:#666;font-size:.85rem}
code{background:#f4f4f4;padding:2px 4px;border-radius:3px}
</style></head><body>
<h1>MoneyScan report</h1>
<p class="meta">Target: <code>{{ data.url }}</code> · HTTP {{ data.status_code }} · Server: {{ data.server or "unknown" }}</p>

{% for f in data.findings %}
<div class="card">
  <span class="sev {{ f.severity }}">{{ f.severity|upper }}</span>
  <h3>{{ f.title }}</h3>
  <p><b>Evidence:</b> <code>{{ f.evidence }}</code></p>
  <p><b>How money leaks:</b> {{ f.why_money }}</p>
  <p><b>Fix:</b> {{ f.fix }}</p>
</div>
{% endfor %}

<p class="meta">Generated by MoneyScan v0.1 — passive checks only.</p>
</body></html>
"""

def write_reports(data, html_path="report.html", json_path="report.json"):
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(Template(HTML_TEMPLATE).render(data=data))
    return html_path, json_path
